name: eagles-postman-newman

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  mayhem-for-api:
    name: Quality Eagles Postman Newman
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Newman and Node version
        run: |
          newman --version
          node --version

      - name: Install newman-reporter-htmlextra
        run: |
          sudo npm install -g newman-reporter-htmlextra

      - name: Execute the collection
        run: newman run ./collection_quality_eagles_t13.json --delay-request 2 --reporters cli,htmlextra --reporter-htmlextra-export ./result/Report.html --globals ./globals_quality_eagles_t13.json

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./result/Report.html