name: eagles-postman-newman

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  run-postman-tests:
    name: Quality Eagles Postman Newman Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Newman and Node version
        run: |
          newman --version
          node --version

      - name: Install newman-reporter-htmlextra
        run: |
          sudo npm install -g newman-reporter-htmlextra

      - name: Run Collection Ítalo
        run: |
          newman run ./Italo-QualityEagles.postman_collection.json \
          --globals ./Italo-QualityEagles.postman_globals.json \
          --delay-request 2 \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export ./result/Report_Collection_Italo.html

      - name: Create result directory
        run: mkdir -p ./result

      - name: Run Collection Jamile
        run: |
          newman run ./Jamile-QualityEagles.postman_collection.json \
          --globals ./Jamile-QualityEagles.postman_globals.json \
          --delay-request 2 \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export ./result/Report_Collection_Jamile.html

      - name: Archive Reports
        run: |
          zip -r ./result/reports.zip ./result/*.html

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ./result/reports.zip
  run-insomnia-tests:
    name: Quality Eagles Insomnia Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0
      - name: Lint
        run: inso lint spec Tadeu-QualityEagles-Collection_Insomnia_2025-02-24.json --ci
      - name: Run test suites
        run: inso run test Tadeu-QualityEagles-Collection_Insomnia_2025-02-24.json --env Tadeu-QualityEagles-Globals_Insomnia_2025-02-24.json --ci
