name: eagles-postman-newman

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run-postman-tests:
    name: Quality Eagles Postman Newman Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print the current working directory
        run: pwd

      - name: List files and find the absolute path of a specific file
        run: |
          echo "Listing the files in the repository:"
          ls -l
          echo "Finding absolute path of specific file:"
          ABSOLUTE_PATH=$(realpath ./insomnia-data/Italo-QualityEagles.postman_globals.json)
          echo "Absolute path: $ABSOLUTE_PATH"

      - name: Check Newman and Node version
        run: |
          newman --version
          node --version

      - name: Install newman-reporter-htmlextra
        run: |
          sudo npm install -g newman-reporter-htmlextra

      - name: Create result directory
        run: mkdir -p ./result

      - name: Ensure /etc/newman/insomnia-data exists
        run: |
          echo "Ensuring the /etc/newman/insomnia-data directory exists..."
          mkdir -p /etc/newman/insomnia-data
          ls -l /etc/newman/insomnia-data

      - name: Verify required files in /etc/newman/insomnia-data
        run: |
          echo "Verifying if the necessary files exist..."
          if [ ! -f "/etc/newman/insomnia-data/Italo-QualityEagles.postman_collection.json" ]; then
            echo "Error: Italo-QualityEagles.postman_collection.json not found!"
            exit 1
          fi
          if [ ! -f "/etc/newman/insomnia-data/Italo-QualityEagles.postman_globals.json" ]; then
            echo "Error: Italo-QualityEagles.postman_globals.json not found!"
            exit 1
          fi

      - name: Run Collection Ítalo
        run: |
          newman run /etc/newman/insomnia-data/Italo-QualityEagles.postman_collection.json \
          --globals /etc/newman/insomnia-data/Italo-QualityEagles.postman_globals.json \
          --delay-request 2 \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export ./result/Report_Collection_Italo.html

      - name: Run Collection Jamile
        run: |
          newman run /etc/newman/insomnia-data/Jamile-QualityEagles.postman_collection.json \
          --globals /etc/newman/insomnia-data/Jamile-QualityEagles.postman_globals.json \
          --delay-request 2 \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export ./result/Report_Collection_Jamile.html

      - name: Archive Reports
        run: zip -r ./result/reports.zip ./result/*.html

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ./result/reports.zip

  run-insomnia-tests:
    name: Quality Eagles Insomnia Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print working directory
        run: pwd

      - name: Ensure insomnia-data directory exists
        run: |
          echo "Ensuring the /etc/newman/insomnia-data directory exists..."
          mkdir -p /etc/newman/insomnia-data
          ls -l /etc/newman/insomnia-data/

      - name: Verify required files in /etc/newman/insomnia-data
        run: |
          echo "Verifying if the necessary files exist..."
          if [ ! -f "/etc/newman/insomnia-data/Tadeu-QualityEagles-Collection.json" ]; then
            echo "Error: Tadeu-QualityEagles-Collection.json not found!"
            exit 1
          fi
          if [ ! -f "/etc/newman/insomnia-data/Tadeu-QualityEagles-Globals.json" ]; then
            echo "Error: Tadeu-QualityEagles-Globals.json not found!"
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup inso
        uses: Kong/setup-inso@v1
        with:
          inso-version: 10.1.1

      - name: Print inso version
        run: inso --version

      - name: Run Insomnia tests
        run: |
          inso run test /etc/newman/insomnia-data/Tadeu-QualityEagles-Collection.json \
          --env /etc/newman/insomnia-data/Tadeu-QualityEagles-Globals.json \
          --workingDir /etc/newman/insomnia-data \
          --verbose --ci
